from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'bd0313f0a534'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('urls')
    op.drop_table('urls_checks')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('urls_checks',
                    sa.Column(
                        'id',
                        sa.BIGINT(),
                        sa.Identity(
                            always=True, start=1, increment=1, minvalue=1,
                            maxvalue=9223372036854775807, cycle=False, cache=1
                        ),
                        autoincrement=True, nullable=False
                    ),
                    sa.Column(
                        'url_id', sa.BIGINT(),
                        autoincrement=False, nullable=True),
                    sa.Column('status_code', sa.INTEGER(),
                              autoincrement=False, nullable=True),
                    sa.Column('h1', sa.TEXT(), autoincrement=False,
                              nullable=True),
                    sa.Column('title', sa.TEXT(), autoincrement=False,
                              nullable=True),
                    sa.Column('description', sa.TEXT(), autoincrement=False,
                              nullable=True),
                    sa.Column('created_at', sa.DATE(),
                              server_default=sa.text('CURRENT_TIMESTAMP'),
                              autoincrement=False, nullable=True),
                    sa.ForeignKeyConstraint(['url_id'], ['urls.id'],
                                            name='urls_checks_url_id_fkey'),
                    sa.PrimaryKeyConstraint('id', name='urls_checks_pkey')
                    )
    op.create_table('urls',
                    sa.Column('id', sa.BIGINT(), sa.Identity(always=True,
                                                             start=1,
                                                             increment=1,
                                                             minvalue=1,
                                                             maxvalue=922337203,
                                                             cycle=False,
                                                             cache=1),
                              autoincrement=True, nullable=False),
                    sa.Column('name', sa.VARCHAR(length=255),
                              autoincrement=False, nullable=False),
                    sa.Column('created_at', sa.DATE(),
                              server_default=sa.text('CURRENT_TIMESTAMP'),
                              autoincrement=False, nullable=True),
                    sa.PrimaryKeyConstraint('id', name='urls_pkey'),
                    sa.UniqueConstraint('name', name='urls_name_key')
                    )
    # ### end Alembic commands ###
